server:
  port: 8889

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/dds1q/sping-cloud-config.git
          uri: file://C:\sparta\study\native-file-repo
# /ecommerce/default

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh